name: Update KEGG Data

on:
  schedule:
    # Run at 00:00 on Sunday (UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rvest
            any::tibble
            any::tidyr
            any::devtools
            local::.
          needs: check

      - name: Install package
        run: |
          Rscript -e 'devtools::install()'

      - name: Update KEGG Data
        run: |
          Rscript -e 'source(system.file("extdata/kegg_pathway_category.r", package="clusterProfiler"))'
          Rscript -e 'clusterProfiler:::get_kegg_species(save=TRUE)'
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update KEGG data"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-kegg-data
          delete-branch: true
          title: 'chore: Update KEGG internal data'
          body: |
            This PR updates the internal KEGG data (`kegg_category.rda` and `kegg_species.rda`).
            
            - Auto-generated by GitHub Actions.
            - Updates `kegg_category` and `kegg_species`.
          labels: |
            automated pr
            data update
